name: Build and Push Docker Image

on:
  release:
    types: [created]

permissions: write-all

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # Path to the Dockerfile and build context (current directory)
          push: true # Push the image to the container registry
          tags: |
            ghcr.io/${{ github.repository_owner }}/webui-privaxy:latest
            ghcr.io/${{ github.repository_owner }}/webui-privaxy:${{ github.event.release.tag_name }}
